// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformersGallery.Models;

namespace PerformersGallery.Migrations
{
    [DbContext(typeof(GalleryContext))]
    [Migration("20190209102331_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerformersGallery.Models.FacePlusPlus.Attributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CastEmotion");

                    b.Property<int?>("EmotionId");

                    b.Property<int?>("GalleryPhotoId");

                    b.HasKey("Id");

                    b.HasIndex("EmotionId");

                    b.HasIndex("GalleryPhotoId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("PerformersGallery.Models.FacePlusPlus.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Anger");

                    b.Property<double>("Disgust");

                    b.Property<double>("Fear");

                    b.Property<double>("Happiness");

                    b.Property<double>("Neutral");

                    b.Property<double>("Sadness");

                    b.Property<double>("Surprise");

                    b.HasKey("Id");

                    b.ToTable("Emotion");
                });

            modelBuilder.Entity("PerformersGallery.Models.Flickr.FlickrPhoto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Farm");

                    b.Property<string>("Owner");

                    b.Property<string>("Secret");

                    b.Property<string>("Server");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("FlickrPhotos");
                });

            modelBuilder.Entity("PerformersGallery.Models.Gallery.GalleryPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoUrl");

                    b.Property<DateTime>("TimeCreated");

                    b.HasKey("Id");

                    b.ToTable("GalleryPhotos");
                });

            modelBuilder.Entity("PerformersGallery.Models.FacePlusPlus.Attributes", b =>
                {
                    b.HasOne("PerformersGallery.Models.FacePlusPlus.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("EmotionId");

                    b.HasOne("PerformersGallery.Models.Gallery.GalleryPhoto")
                        .WithMany("FacesFound")
                        .HasForeignKey("GalleryPhotoId");
                });
#pragma warning restore 612, 618
        }
    }
}
